# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e416ca52ab4dab0e4eac09e597efa4995cddef78e01e8de5661a6506a3804f8bda43469696edb95e1939f2cc860094e120b3161a5df5e73dac6335d67d53b01

test:
  secret_key_base: 4b0065835c1e26f68df0807c694504a54eee32cd6d6693667543e8c9b3150256fa6ed313d303d102d8cc2585ab331104cd9202dc0ca64aa4cfccaba7d8e7ee27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
